spring:
  datasource:
    username: zhangsan
    password: 123456
    url: jdbc:mysql://192.168.136.110:3306/springboot?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    #driver-class-name: com.mysql.jdbc.Driver
    driver-class-name: com.mysql.cj.jdbc.Driver
    #type: com.alibaba.druid.pool.DruidDataSource


  jpa:
    #指定数据库提供商
    database: mysql
    #打印SQL
    show-sql: true
    #是jpa层面对数据表生成策略的控制（要不要根据实体对象来生成数据库表的映射-正向开发）
    generate-ddl: true
    hibernate:
      #是jpa实现hibernate层面上对数据表生成策略的控制
      #(update含义：表在就不生成，表不在就生成；实体类修改了会自动更新，并且数据不会丢失)
      ddl-auto: update
      #指定命名策略
      naming_strategy: org.hibernate.cfg.ImprovedNamingStrategy
  main:
    allow-bean-definition-overriding: true
  redis:
    port: 6379
    host: 192.168.136.110
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false


mybatis:
  config-location: classpath:/mybatis/mybatis-config.xml #指定主配置文件
  mapper-locations: classpath:/mybatis/mapper/*.xml # 指定xml映射文件路径
  type-aliases-package: com.atguigu.domain # 指定mybatis别名包
logging:
  level:
    com.atguigu.dao: debug # 配置日志